# Copyright (c) 2025 LATMOS (France, UMR 8190) and IGE (France, UMR 5001).
#
# License: BSD 3-clause "new" or "revised" license (BSD-3-Clause).
#
# GitHub workflow to run unit tests for run/commons.bash.

name: Unit tests (commons.bash)
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'run/commons.bash'
      - 'run/test_commons.bash'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run the unit tests
        run: |
          cd ${{ github.workspace }}/run
          chmod 500 ./test_commons.bash
          ./test_commons.bash
